"""fig_features — composite "PyGROG features at a glance" panel.

Tiles the six per-feature figures generated by the standalone scripts into
a single 2x3 poster panel:

    +------------------+------------------+--------------------+
    | Brain recon      | ORC              | Subspace coeffs    |
    +------------------+------------------+--------------------+
    | Solver curves    | Toeplitz speedup | Multi-framework    |
    +------------------+------------------+--------------------+

If any source PNG is missing, the corresponding ``fig_*.py`` script is
invoked first so this file is self-contained.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import FIGURES_DIR, POSTER_STYLE, save_fig

SCRIPTS_DIR = Path(__file__).resolve().parent

PANELS = [
    ("fig_brain_recon", "Non-Cartesian recon  (GROG → SparseFFT vs FINUFFT)"),
    ("fig_orc", "Off-resonance correction"),
    ("fig_subspace", "Subspace projection (T2 mapping)"),
    ("fig_solvers", "Iterative solvers  (CG · LSMR · PCG)"),
    ("fig_toeplitz", "Toeplitz $A^H A$ vs nested forward+adjoint"),
    ("fig_interop", "Native interop  (sigpy · deepinv · mrpro)"),
]


def _ensure_source(name: str) -> Path:
    out = FIGURES_DIR / f"{name}.png"
    if not out.exists():
        script = SCRIPTS_DIR / f"{name}.py"
        print(f"[fig_features] {out.name} missing — running {script.name}…")
        subprocess.run([sys.executable, str(script)], check=True)  # noqa: S603
    return out


def main() -> None:
    images = [(label, _ensure_source(name)) for name, label in PANELS]
    with POSTER_STYLE():
        fig, axes = plt.subplots(2, 3, figsize=(20, 10.5))
        for ax, (label, path) in zip(axes.ravel(), images, strict=False):
            img = mpimg.imread(path)
            ax.imshow(img)
            ax.set_xticks([])
            ax.set_yticks([])
            for s in ax.spines.values():
                s.set_visible(False)
            ax.set_title(label, fontsize=16, pad=8)
        fig.suptitle("PyGROG features at a glance", fontsize=24, y=1.00)
        fig.tight_layout()
        save_fig(fig, "fig_features")


if __name__ == "__main__":
    main()
